### ISSUE TITLE
why there is no script in this respitory?

### ISSUE THREAD

**Issue by y9c** [saccharome/CBC#1]
The Sci Rep. [paper](http://www.nature.com/articles/srep29543):

> The scripts used for data processing are available in the GitHub repository (https://github.com/saccharome/CBC).

**Comment by jaderarmanhi** [comment]
Dear yech1990,
Unfortunately we have faced some issues when preparing our scripts, and turns out that we are spending more time than expected. We are polishing the scripts from personal comments and customization in order to make them available for any user. Also we are preparing a short dataset to help users to test scripts, as well as a tutorial to help users in installation and dependencies. We are doing our best to make it online in no more than 2 weeks from now. We apologize for the inconvenience.

**Comment by y9c** [comment]
@jaderarmanhi
Thank you for your reply.
Looking forward to read the code.

**Comment by y9c** [comment]
Hi @jaderarmanhi  
Any progress?

**Comment by jaderarmanhi** [comment]
Dear yech1990,
We apologize for delaying our upload. We had some problems with our servers. We have now uploaded the scripts. Please let us know if you have any problems.
